name: Close README-only PRs

on:
  pull_request_target:
    types: 
      - opened
      - edited
      - synchronize

jobs:
  close_readme_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for README-only changes
        id: check_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }})
          if [[ $changed_files == *"README.md"* && $changed_files =~ ^README.md$ ]]; then
            echo "::set-output name=readme_only::true"
          fi

      - name: Close pull request
        if: ${{ steps.check_changes.outputs.readme_only == 'true' }}
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "This pull request only modifies the README.md file. We generally don't accept such PRs unless they contribute significant value."
