name: Close README-only PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  check_files:
    if: ${{ !github.actor == 'dependabot[bot]' }} 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v5
    - name: Check if only README changed
      if: contains(steps.changed-files.outputs.all, 'README.md') && steps.changed-files.outputs.count == 1
      uses: thomaseizinger/close-pull-request@v1
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        comment: Closing this PR as only the README was updated.
